from building import *
import os

cwd = GetCurrentDir()

src = Glob('*.c')
port_src = Glob('platform/*.c')

SrcRemove(src, ['i_video.c'])
SrcRemove(src, ['i_videohr.c'])

path =  [cwd]
path += [cwd + '/platform']

group = DefineGroup('Doom_port', port_src, depend = ['BSP_USING_LCD'], CPPPATH = path)
group = group + DefineGroup('Doom_source', src, depend = ['BSP_USING_LCD'], CPPPATH = path)
Return('group')
