import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = Glob('*.c')

CPPDEFINES = ['ARM_MATH_CM85', '__FPU_PRESENT = 1']

objs = DefineGroup('openmv/rtt-port', src, depend = ['BSP_USING_OPENMV'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
