import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = Glob('*.c')

objs = DefineGroup('openmv/rtt-port', src, depend = ['BSP_USING_OPENMV'], CPPPATH = CPPPATH)

Return('objs')
