
from building import *
import rtconfig

cwd = GetCurrentDir()
src = ['ospi_b_commands.c']
src += ['drv_w25qxx.c']
# src += ['ospi_b_ep.c']

CPPPATH = [cwd]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

group = DefineGroup('ext-flash', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
